language: android

android:
  components:
    - build-tools-28
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

install:
  - true

script:
  - ./gradlew clean build test check
